# Creación de Deployment Basic
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: VAR_1
          value: "Jhordan"
        - name: VAR_2
          value: "Escobar"
        - name: VAR_3
          valueFrom:
            fieldRef:
            fieldPath: status.hostIP
        resources:
          requests:
          memory: "64Mi"
          cpu: "200m"
          limits:
          memory: "128Mi"
          cpu: "500m"
        readinessProbe:
          httpGet:
          path: /
          port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 80 